In [2]:
import pandas as pd

Read the csv file from this url:
'https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=drive_link'

Name it `sets_df`

In [4]:
url = 'https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
sets_df = pd.read_csv(path)
sets_df

,set_num,name,year,theme_id,num_parts
0,TRUFRIENDS-1,Wishing Well,2017,494,33
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
2,71005-15,Chief Wiggum,2014,550,6
3,6593-1,Blaze Battler,1991,74,126
4,75916-1,Dilophosaurus Ambush,2015,602,246
...,...,...,...,...,...
995,1668-1,Basic Building Set Trial Size,1992,469,30
996,71237-1,Aquaman and Aqua Watercraft,2016,604,43
997,3939-1,Mia's Bedroom,2012,494,86
998,5161-1,Inverted Slope Bricks,1987,443,16
999,10223-1,Kingdoms Joust,2012,196,1574

##### Hint

In [ ]:
# url = ___________
# path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
# sets_df = pd.read_csv(_______)

#### Exercise 1
Display the basic information about DataFrames `sets_df`  Check the number of rows, columns, data types, and non-null counts.

In [45]:
sets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   set_num    1000 non-null   object
 1   name       1000 non-null   object
 2   year       1000 non-null   int64
 3   theme_id   1000 non-null   int64
 4   num_parts  1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

#### Exercise 2
Show the first 5 rows of the DataFrame to get an initial idea about the data. Then show the first 7 instead.

In [13]:
sets_df.head()

,set_num,name,year,theme_id,num_parts
0,TRUFRIENDS-1,Wishing Well,2017,494,33
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
2,71005-15,Chief Wiggum,2014,550,6
3,6593-1,Blaze Battler,1991,74,126
4,75916-1,Dilophosaurus Ambush,2015,602,246

#### Exercise 3
Display the summary statistics of the numerical columns in `sets_df`.

In [15]:
sets_df.describe()

              year     theme_id    num_parts
count  1000.000000  1000.000000  1000.000000
mean   2002.080000   316.247000   155.721000
std      13.650932   178.049194   289.391601
min    1954.000000     1.000000     0.000000
25%    1997.000000   163.750000     8.000000
50%    2006.000000   333.500000    45.000000
75%    2013.000000   478.000000   171.250000
max    2017.000000   616.000000  2741.000000

#### Exercise 4
Print out a sentence that shows number of rows and columns.  
\
Get the numbers of rows and columns using `.shape`.  
Save the number of columns in a variable `num_cols` and number of rows in a variable `num_rows`.  
Use those variables in your `print()` function.   

The sentence should look like this (the numbers should not be hardcoded - they need to come from the variables):  
**"This dataset has 1000 rows and 5 columns"**

In [25]:
sets_df.shape

(1000, 5)

In [27]:
num_cols = sets_df.shape[1]
num_rows = sets_df.shape[0]

print(f"This dataset has {num_rows} rows and {num_cols} columns")

This dataset has 1000 rows and 5 columns

#### Exercise 5
Select the column `year`

In [33]:
sets_df['year']

0      2017
1      2011
2      2014
3      1991
4      2015
       ...
995    1992
996    2016
997    2012
998    1987
999    2012
Name: year, Length: 1000, dtype: int64

#### Exercise 6
Select all unique years from the column `year` using `.unique()`.

In [39]:
sets_df['year'].unique()

array([2017, 2011, 2014, 1991, 2015, 2009, 1957, 1974, 1990, 2003, 2012,
       2010, 1999, 1997, 2002, 2004, 1995, 1993, 1963, 1982, 1967, 2013,
       1989, 2005, 1998, 1987, 1985, 2007, 1996, 2001, 2016, 1954, 1994,
       1966, 2000, 2006, 2008, 1986, 1977, 1984, 1955, 1958, 1969, 1983,
       1956, 1976, 1970, 1979, 1988, 1992, 1973, 1962, 1972, 1978, 1968,
       1980, 1965, 1964, 1981, 1975, 1961, 1971])

#### Exercise 7
Select the earliest year by using `.min()`

In [40]:
sets_df['year'].min()

1954

#### Exercise 8
Select the latest year by using `.max()`

In [41]:
sets_df['year'].max()

2017

#### Exercise 9
How many different themes are represented?

In [46]:
sets_df['theme_id'].nunique()

337

#### Exercise 10
What's the largest number of pieces in one set? The smallest?

In [52]:
sets_df['num_parts'].max()
#sets_df['num_parts'].min()

0

#### Exercise 11
Select 10 random entries from the DataFrame.

In [55]:
sets_df.sample(10)

     set_num                            name  year  theme_id  num_parts
554   1352-1                Explosion Studio  2000       273        237
57    7950-1               Knight's Showdown  2010       196         61
694   7587-1                    Pony Jumping  2008       323         57
173  30213-1           Gandalf at Dol Guldur  2012       563         31
287   7680-1  The Twilight - Limited Edition  2008       165        887
856  60070-1               Water Plane Chase  2015        61        261
529   2849-1                      Helicopter  1997        68         20
723   8098-1                Clone Turbo Tank  2010       165       1142
924    208-1       Mother with Baby Carriage  1978       364         46
261  45100-1          Story Starter Core Set  2013       507       1145

#### Exercise 12
What's the most common number of pieces in a set?

In [62]:
sets_df['num_parts'].mode()

0    0
Name: num_parts, dtype: int64

#### Exercise 13
Which five years have the most sets associated with them?

In [66]:
sets_df['year'].value_counts().head()

year
2014    71
2015    66
2013    58
2012    46
2010    46
Name: count, dtype: int64

#### Exercise 14
Are all `set_num` values unique? Compare the number of unique `set_num` values to the number of rows in the DataFrame.

In [71]:
sets_df['set_num'].nunique() == sets_df.shape[0]

True