In [428]:
import pandas as pd

Read the csv file from this url:
'https://drive.google.com/file/d/1bCnDYPEwBIRox737Sgk0FNp89vWT2YnQ/view?usp=drive_link'

Name it `sets_df`

In [429]:
# Your code here
url = 'https://drive.google.com/file/d/1bCnDYPEwBIRox737Sgk0FNp89vWT2YnQ/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
sets_df = pd.read_csv(path)

> Make sure you save the changes by overwriting the original DataFrame:  
e.g. `df = df.drop_duplicates()`

In [430]:
sets_df = sets_df.drop_duplicates()
sets_df

,s,n,y,ti,np,q
0,TRUFRIENDS-1,Wishing Well,2017,494,33.0,1
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9.0,1
2,71005-15,Chief Wiggum,2014,550,6.0,1
3,6593-1,Blaze Battler,1991,74,NaN,1
4,75916-1,Dilophosaurus Ambush,2015,602,246.0,1
...,...,...,...,...,...,...
975,385-1,Jeep CJ-5,1976,397,58.0,1
976,41305-1,Emma's Photo Studio,2017,494,95.0,1
977,30447-1,Captain America's Motorcycle,2016,493,25.0,1
978,71002-11,Scientist - Complete Set,2013,547,7.0,1
979,3703-1,Peter Pig the Cook,1982,390,3.0,1

#### Exercise 1
Explore the `sets_df` with `.info()`

In [431]:
# Your code
sets_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 980 entries, 0 to 979
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   s       980 non-null    object
 1   n       980 non-null    object
 2   y       980 non-null    int64
 3   ti      980 non-null    int64
 4   np      974 non-null    float64
 5   q       980 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 53.6+ KB

#### Exercise 2
Rename the columns:  
s -> set_num  
n -> name  
y -> year  
ti -> theme_id  
np -> num_parts  
q -> qty  

> **Hint:** You can do it either by using `.rename()` method or by setting `.columns` attribute directly to a list of new names.

In [432]:

#  alternative
# sets_df.rename(columns={'s':'set_num', 'n':'name', 'y':'year', 'ti':'theme_id', 'np':'num_parts','q':'qty'})

sets_df.columns = ['set_num', 'name', 'year', 'theme_id', 'num_parts','qty']

Review the change

In [433]:
# Your code here
sets_df

,set_num,name,year,theme_id,num_parts,qty
0,TRUFRIENDS-1,Wishing Well,2017,494,33.0,1
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9.0,1
2,71005-15,Chief Wiggum,2014,550,6.0,1
3,6593-1,Blaze Battler,1991,74,NaN,1
4,75916-1,Dilophosaurus Ambush,2015,602,246.0,1
...,...,...,...,...,...,...
975,385-1,Jeep CJ-5,1976,397,58.0,1
976,41305-1,Emma's Photo Studio,2017,494,95.0,1
977,30447-1,Captain America's Motorcycle,2016,493,25.0,1
978,71002-11,Scientist - Complete Set,2013,547,7.0,1
979,3703-1,Peter Pig the Cook,1982,390,3.0,1

#### Exercise 3
Check if there are any null values in the dataset

In [434]:
# Your code here
sets_df.isnull().sum()

set_num      0
name         0
year         0
theme_id     0
num_parts    6
qty          0
dtype: int64

#### Exercise 4
There are 6 null values in the `'num_parts'` column.  
Find the mean of that column using `.mean()`.  
Fill the null values with the mean using `.fillna()`.  
Check once again if there are any null values.

In [435]:
# Your code here
sets_df.loc[:,'num_parts']=sets_df['num_parts'].fillna(sets_df["num_parts"].mean())
sets_df
sets_df.isnull().sum()

set_num      0
name         0
year         0
theme_id     0
num_parts    0
qty          0
dtype: int64

#### Exercise 5
Check if there are any duplicated rows using `.duplicated()`.  
If there are, drop them.  
Check again if there are any duplicates left.

In [436]:
sets_df.duplicated().sum()

np.int64(0)

In [437]:
sets_df = sets_df.drop_duplicates()

In [438]:
sets_df.duplicated().sum()

np.int64(0)

#### Exercise 6
Explore the column `qty`.    
Think about why this column is not usefull to us and then drop it.

In [439]:
# Your code here
sets_df['qty'].describe()
# or
# sets_df['qty'].unique()

count    980.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: qty, dtype: float64

In [440]:
sets_df = sets_df.drop('qty',axis=1)

#### Exercise 7
There is a small dataset of extra lego sets. Using `pd.concat()` concatinate it with `sets_df` so that `extra_sets` becomes part of `sets_df`.  
Make sure the index stays unique in the end.

In [441]:
url = 'https://drive.google.com/file/d/1uIsCZ4Y9ntUOsLiaynSVO28Ba1KrS3D8/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
extra_sets = pd.read_csv(path)
extra_sets

,set_num,name,year,theme_id,num_parts
0,1094-1,Johnny Thunder,1999,297,13.0
1,3642-1,Fire Engine,1985,395,18.0
2,7724-14,Advent Calendar 2008 City (Day 13) Diver and S...,2008,220,1.0
3,264-1,Living Room Set,1974,405,241.0
4,70736-1,Attack of the Morro Dragon,2015,435,655.0
5,8803-0,Minifigure Series 3 [Random Bag],2011,538,0.0
6,71008-4,Snake Charmer,2015,551,7.0
7,3829-1,Fire Nation Ship,2006,317,724.0
8,30108-1,Summer Picnic,2013,494,33.0
9,71001-7,Bumblebee Girl - Complete Set,2013,545,7.0
10,41563-1,Splasho,2016,588,67.0
11,4478-2,Geonosian Fighter Blue Box,2004,167,153.0
12,65579-1,Knights' Kingdom Value Pack 8770 and 8771 with...,2004,198,3.0
13,9491-1,Geonosian Cannon,2012,165,133.0
14,7979-5,Advent Calendar 2008 Castle (Day 4) - White S...,2008,219,7.0
15,1668-1,Basic Building Set Trial Size,1992,469,30.0
16,71237-1,Aquaman and Aqua Watercraft,2016,604,43.0
17,3939-1,Mia's Bedroom,2012,494,86.0
18,5161-1,Inverted Slope Bricks,1987,443,16.0
19,10223-1,Kingdoms Joust,2012,196,1574.0

In [442]:
# Your code here
sets_df=pd.concat([sets_df,extra_sets], ignore_index=True)
sets_df

,set_num,name,year,theme_id,num_parts
0,TRUFRIENDS-1,Wishing Well,2017,494,33.000000
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9.000000
2,71005-15,Chief Wiggum,2014,550,6.000000
3,6593-1,Blaze Battler,1991,74,749.979466
4,75916-1,Dilophosaurus Ambush,2015,602,246.000000
...,...,...,...,...,...
995,1668-1,Basic Building Set Trial Size,1992,469,30.000000
996,71237-1,Aquaman and Aqua Watercraft,2016,604,43.000000
997,3939-1,Mia's Bedroom,2012,494,86.000000
998,5161-1,Inverted Slope Bricks,1987,443,16.000000
999,10223-1,Kingdoms Joust,2012,196,1574.000000

#### Exercise 8
The Lego set with `set_num` '70905-1' has a strange number of parts.  
Think about what would be the best value to replace the strange one with and then change it.

In [443]:
# Your code here
sets_df.loc[sets_df['set_num']== '70905-1',:]

     set_num           name  year  theme_id  num_parts
198  70905-1  The Batmobile  2017       484   580000.0

In [444]:
sets_df.loc[sets_df['set_num']=='70905-1','num_parts'] = 580
sets_df.loc[sets_df['set_num']=='70905-1',:]

     set_num           name  year  theme_id  num_parts
198  70905-1  The Batmobile  2017       484      580.0

#### Exercise 9
The Lego set with set_num '1873-1' has a strange value in `year`  
Think about what would be the best value to replace the strange one with and then change it.

In [445]:
# Your code here
sets_df.loc[sets_df['set_num']== '1873-1',:]

    set_num             name  year  theme_id  num_parts
779  1873-1  Pirate Treasure    94       148       49.0

In [446]:
sets_df.loc[sets_df['set_num']== '1873-1','year']=1994
sets_df.loc[sets_df['set_num']== '1873-1',:]

    set_num             name  year  theme_id  num_parts
779  1873-1  Pirate Treasure  1994       148       49.0

### Exercise 10
Organize the Lego sets first by release year and then by theme.      
Reset the index after.

In [447]:
# Your code here
sets_df=sets_df.sort_values(['year','theme_id']).reset_index(drop=True)
sets_df

,set_num,name,year,theme_id,num_parts
0,700.C.3-1,Individual 1 x 6 x 3 Shutter Window (with glass),1954,371,4.0
1,700.20-1,Individual 2 x 10 Bricks,1954,371,5.0
2,1248-2,Painted Trees and Bushes,1955,371,6.0
3,1247-2,Esso Pumps/Sign,1955,371,2.0
4,224-1,2 x 2 & 2 x 4 Curved Bricks,1956,371,14.0
...,...,...,...,...,...
995,41592-1,The Hulk,2017,610,93.0
996,71018-11,Retro Spaceman,2017,611,7.0
997,71018-10,Battle Dwarf,2017,611,9.0
998,70615-1,Fire Mech,2017,616,921.0
999,70614-1,Lightning Jet,2017,616,859.0

### Exercise 11
It has been decided that theme should be incorporated into the set number.    
Make a new column combining the two and call it `combined_id`. The resulting value should have the form    
`theme_id/set_num`       
The new column should appear on the left of the DataFrame (column index 0). `set_num` and `theme_id` should not appear in the final DataFrame.

In [448]:
# Your code here
sets_df['set_num'].info()
sets_df['theme_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: set_num
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: theme_id
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [449]:
sets_df['combined_id'] =sets_df['theme_id'].astype('str')+ ' ' '/' ' ' +  sets_df['set_num']
sets_df=sets_df.drop(['set_num', 'theme_id'], axis=1)
sets_df=sets_df[['combined_id','name','year','num_parts']]
sets_df

,combined_id,name,year,num_parts
0,371 / 700.C.3-1,Individual 1 x 6 x 3 Shutter Window (with glass),1954,4.0
1,371 / 700.20-1,Individual 2 x 10 Bricks,1954,5.0
2,371 / 1248-2,Painted Trees and Bushes,1955,6.0
3,371 / 1247-2,Esso Pumps/Sign,1955,2.0
4,371 / 224-1,2 x 2 & 2 x 4 Curved Bricks,1956,14.0
...,...,...,...,...
995,610 / 41592-1,The Hulk,2017,93.0
996,611 / 71018-11,Retro Spaceman,2017,7.0
997,611 / 71018-10,Battle Dwarf,2017,9.0
998,616 / 70615-1,Fire Mech,2017,921.0
999,616 / 70614-1,Lightning Jet,2017,859.0