In [2]:
import pandas as pd

Read the csv file from this url:
'https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=drive_link'

Name it `sets_df`

In [3]:
#Your code here
url='https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
sets_df = pd.read_csv(path)

#### Exercise 1
How many sets were released in each year?

In [4]:
#Your code here
sets_df
df=sets_df.copy()
df

,set_num,name,year,theme_id,num_parts
0,TRUFRIENDS-1,Wishing Well,2017,494,33
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
2,71005-15,Chief Wiggum,2014,550,6
3,6593-1,Blaze Battler,1991,74,126
4,75916-1,Dilophosaurus Ambush,2015,602,246
...,...,...,...,...,...
995,1668-1,Basic Building Set Trial Size,1992,469,30
996,71237-1,Aquaman and Aqua Watercraft,2016,604,43
997,3939-1,Mia's Bedroom,2012,494,86
998,5161-1,Inverted Slope Bricks,1987,443,16
999,10223-1,Kingdoms Joust,2012,196,1574

In [5]:
df.groupby('year').set_num.count()

year
1954     2
1955     2
1956     1
1957     1
1958     5
        ..
2013    58
2014    71
2015    66
2016    37
2017    34
Name: set_num, Length: 62, dtype: int64

#### Exercise 2
In which five years were the most sets released?

In [6]:
#Your code here
df.groupby('year').set_num.count().sort_values(ascending=False).head(5)
#alternative
# sets_df.groupby('year').set_num.count().nlargest(5)

year
2014    71
2015    66
2013    58
2010    46
2012    46
Name: set_num, dtype: int64

#### Exercise 3
What is the median number of parts and the number of sets in each theme?

In [7]:
#Your code here
df.groupby('theme_id').agg({'num_parts':'median','set_num':'count'})

          num_parts  set_num
theme_id
1             250.0       14
3              78.0        3
5             353.0        1
6             308.0        1
7             595.0        5
...             ...      ...
605          1184.0        1
606           615.0        1
610            93.0        1
611             8.0        2
616           890.0        2

[337 rows x 2 columns]

#### Exercise 4
In which year(s) were the most sets released under a single theme?

In [8]:
#Your code here
df.groupby(['year','theme_id']).set_num.count().nlargest()

# alternative
# sets_df.groupby(['year', 'theme_id']).set_num.count().sort_values(ascending=False)

year  theme_id
1966  371         7
2014  504         7
1987  443         6
2001  273         6
2005  220         6
Name: set_num, dtype: int64

#### Load more data
Run the cell below to load more DataFrames for practice on merging.

In [9]:
def read_data(id):
    return pd.read_csv('https://drive.google.com/uc?export=download&id='+id_dict[id])

id_dict = {
    'sets': '1Dkd09FsucudaWVPkTHRV8Wx_GachJLI1',
    'inventories': '1CoBbtb0XuVcQLk_EqfeQKcfY8EuClOcg',
    'inventory_minifigs': '1e3eogAYpdz0-B_ccdVkfbwOVyNXOckn5',
    'minifigs': '1NOs2Lrxn4Kp-731q8dpBDZkzYpK6WuFm',
    'themes': '1y_RE8f-J91DQBA8qaP-xVlKb_ZZe8ky_',
}

sets_df = read_data('sets')
inventories_df = read_data('inventories')
inventory_minifigs_df = read_data('inventory_minifigs')
minifigs_df = read_data('minifigs')
themes_df = read_data('themes')

Explore all the available DataFrames to get an idea of how they might be merged.

In [10]:
inventory_minifigs_df

       inventory_id     fig_num  quantity
0                 3  fig-001549         1
1                 4  fig-000764         1
2                19  fig-000555         1
3                25  fig-000574         1
4                26  fig-000842         1
...             ...         ...       ...
21765        218785  fig-004793         1
21766        218785  fig-004794         1
21767        218785  fig-004795         1
21768        219601  fig-006021         1
21769        219685  fig-014780         1

[21770 rows x 3 columns]

In [11]:
#Your code here
df.info()
themes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   set_num    1000 non-null   object
 1   name       1000 non-null   object
 2   year       1000 non-null   int64
 3   theme_id   1000 non-null   int64
 4   num_parts  1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      460 non-null    int64
 1   name    460 non-null    object
dtypes: int64(1), object(1)
memory usage: 7.3+ KB

###### **Hint:**

Use something like `.info()` or `.columns` to search for common names.

In [12]:
themes_df.columns
sets_df.columns
inventories_df.columns
inventory_minifigs_df.columns
minifigs_df.columns

Index(['fig_num', 'name', 'num_parts', 'img_url'], dtype='object')

#### Exercise 5
What is the name of the theme with the most sets associated?

In [13]:
df.merge(themes_df,left_on='theme_id',right_on='id',suffixes=('_set', '_theme')).groupby('name_theme')['set_num'].count().nlargest(1)

name_theme
Technic    36
Name: set_num, dtype: int64

#### Exercise 6
What minifigs are in the set 'Traitor Transport (with Cave)'?    

> If two DataFrames have a column of the same name (other than the merging column), you can control the columns' names in the output by using the parameter `suffixes` in the merge.

In [23]:
#Your code here
(
    df
    .loc[sets_df['name'] == 'Traitor Transport (with Cave)']
    .merge(inventories_df)
    .merge(inventory_minifigs_df, left_on='id', right_on='inventory_id')
    .merge(minifigs_df, on='fig_num', suffixes=('_set', '_fig'))
    [['name_fig']]
)

Empty DataFrame
Columns: [name_fig]
Index: []

In [15]:
df

,set_num,name,year,theme_id,num_parts
0,TRUFRIENDS-1,Wishing Well,2017,494,33
1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
2,71005-15,Chief Wiggum,2014,550,6
3,6593-1,Blaze Battler,1991,74,126
4,75916-1,Dilophosaurus Ambush,2015,602,246
...,...,...,...,...,...
995,1668-1,Basic Building Set Trial Size,1992,469,30
996,71237-1,Aquaman and Aqua Watercraft,2016,604,43
997,3939-1,Mia's Bedroom,2012,494,86
998,5161-1,Inverted Slope Bricks,1987,443,16
999,10223-1,Kingdoms Joust,2012,196,1574

#### Exercise 7
Which set has the has the highest version number?

In [16]:
#Your code here
df.merge(inventories_df.nlargest(1, 'version'))

Empty DataFrame
Columns: [set_num, name, year, theme_id, num_parts, id, version]
Index: []

#### Exercise 8
How many minifigs are the set "Mos Eisley Cantina" (2020)?     
Which minifig appears most in that set? (Try to get a picture of it.)

In [19]:
(
    sets_df.query('(name == "Mos Eisley Cantina")&(year == 2020)')
    .merge(inventories_df)
    .merge(inventory_minifigs_df, left_on='id', right_on='inventory_id')
    .quantity.sum()
)

np.int64(21)

In [22]:
#Your code here
(
    sets_df.query('(name == "Mos Eisley Cantina")&(year == 2020)')
    .merge(inventories_df)
    .merge(inventory_minifigs_df, left_on='id', right_on='inventory_id')
    .nlargest(1, 'quantity')
    .merge(minifigs_df, on='fig_num')
    [['name_y', 'img_url']]
)

          name_y                                            img_url
0  Bith Musician  https://cdn.rebrickable.com/media/sets/fig-004...